 
version: '3'
services:
    web:
        image: nginx:latest
        env_file: .env
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/templates/default.conf.template
            - ./app:/app
            - ./.htpasswd:/etc/nginx/.htpasswd
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        env_file: .env
        environment:
            - MYSQL_HOST=mysql
        volumes:
            - ./app:/app
        links:
            - mysql
        depends_on:
            - mysql

    mysql:
        image: mariadb:latest
        env_file: .env
        volumes:
            - ./mysqldata:/var/lib/mysql
            - ./ouvidoria.sql:/docker-entrypoint-initdb.d/dump.sql
